/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { CrearEventoRequest } from './models/crear-evento-request';
export { EditarEventoRequest } from './models/editar-evento-request';
export { EliminarEventoRequest } from './models/eliminar-evento-request';
export { GestionEventosEve } from './models/gestion-eventos-eve';
export { HistorialModificacionEve } from './models/historial-modificacion-eve';
export { InscribirEventoRequest } from './models/inscribir-evento-request';
export { InscripcionesEvt } from './models/inscripciones-evt';
export { LoginRequest } from './models/login-request';
export { UsuariosDatosGenerales } from './models/usuarios-datos-generales';
