/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ServicioGestionEventosService } from './services/servicio-gestion-eventos.service';
export { UserService } from './services/user.service';
