/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CrearEventoRequest {
  capacidadMaxima?: number;
  descripcion?: string | null;
  fechaHora?: string;
  idUsuario?: number;
  nombre?: string | null;
  ubicacion?: string | null;
}
