/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EditarEventoRequest {
  capacidadMaxima?: number;
  fechaHora?: string;
  idEvento?: number;
  idUsuario?: number;
  ubicacion?: string | null;
}
