/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HistorialModificacionEve } from '../models/historial-modificacion-eve';
import { InscripcionesEvt } from '../models/inscripciones-evt';
import { UsuariosDatosGenerales } from '../models/usuarios-datos-generales';
export interface GestionEventosEve {
  capacidadMaxima?: number;
  descripcion?: string | null;
  estado?: boolean;
  fechaActualizacion?: string | null;
  fechaCreacion?: string;
  fechaHora?: string;
  historialModificacionEves?: Array<HistorialModificacionEve> | null;
  idEvento?: number;
  idUsuario?: number;
  idUsuarioNavigation?: UsuariosDatosGenerales;
  inscripcionesEvts?: Array<InscripcionesEvt> | null;
  nombreEvento?: string | null;
  ubicacion?: string | null;
  usuarioActualizacion?: number | null;
  usuarioCreacion?: number;
}
