/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GestionEventosEve } from '../models/gestion-eventos-eve';
import { UsuariosDatosGenerales } from '../models/usuarios-datos-generales';
export interface HistorialModificacionEve {
  descripcionModificacion?: string | null;
  estado?: boolean;
  fechaActualizacion?: string | null;
  fechaCreacion?: string;
  fechaModificacion?: string;
  idEvento?: number;
  idEventoNavigation?: GestionEventosEve;
  idModificacion?: number;
  idUsuario?: number;
  idUsuarioNavigation?: UsuariosDatosGenerales;
  usuarioActualizacion?: number | null;
  usuarioCreacion?: number;
}
