/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InformacionEvento {
  capacidadMaxima?: number;
  descripcion?: string | null;
  estaInscrito?: number;
  estadoEvento?: boolean;
  fechaHora?: string;
  idEvento?: number;
  idUsuario?: number;
  nombreEvento?: string | null;
  totalUsuarios?: number;
  ubicacion?: string | null;
}
