/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UsuarioGestionEventos {
  claveUsuario?: string | null;
  cnameUsuario?: string | null;
  correo_Usuario?: string | null;
  estado?: boolean;
  fechaActualizacion?: string | null;
  fechaCreacion?: string;
  id_Usuario?: number;
  nombre_Usuario?: string | null;
  usuarioActualizacion?: number;
  usuarioCreacion?: number;
}
