/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GestionEventosEve } from '../models/gestion-eventos-eve';
import { HistorialModificacionEve } from '../models/historial-modificacion-eve';
import { InscripcionesEvt } from '../models/inscripciones-evt';
export interface UsuariosDatosGenerales {
  correoUsuario?: string | null;
  estado?: boolean;
  fechaActualizacion?: string | null;
  fechaCreacion?: string;
  gestionEventosEves?: Array<GestionEventosEve> | null;
  historialModificacionEves?: Array<HistorialModificacionEve> | null;
  idUsuario?: number;
  inscripcionesEvts?: Array<InscripcionesEvt> | null;
  nombreUsuario?: string | null;
  usuarioActualizacion?: number | null;
  usuarioCreacion?: number;
}
