/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InformacionEvento } from '../../models/informacion-evento';

export interface ApiServicioGestionEventosObtenerPost$Params {
      body?: number
}

export function apiServicioGestionEventosObtenerPost(http: HttpClient, rootUrl: string, params?: ApiServicioGestionEventosObtenerPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<InformacionEvento>>> {
  const rb = new RequestBuilder(rootUrl, apiServicioGestionEventosObtenerPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<InformacionEvento>>;
    })
  );
}

apiServicioGestionEventosObtenerPost.PATH = '/api/ServicioGestionEventos/obtener';
